apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
    run: nfs
spec:
  volumes:
    - name: pvc-nfs
      persistentVolumeClaim:
        claimName: pvc-nfs
  containers:
    - name: app
      image: alpine
      volumeMounts:
        - name: pvc-nfs
          mountPath: "/mnt"
      env:
      - name: TZ
        value: "Asia/Tehran"    
      command: ["/bin/sh"]
      # args: ["-c","while true; do cat /proc/meminfo | grep MemFree >> /mnt/memory.txt; sleep 5; done"]
      args: ["-c","while true; do date +%H:%M:%S >> /mnt/time.txt; sleep 5; done"]
  imagePullSecrets:
    - name: regcred 
  nodeSelector:
    key: master     
