apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  # namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client   
  resources:
    requests:
      storage: 1Gi
