apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
    # department: sales
  ports:
  - protocol: TCP
    port: 8080
    #target port pod listening
    targetPort: 8080