
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vault-demo
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'devweb-app'
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-inject-secret-config.txt: 'secret/data/devwebapp/config'
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- with secret "secret/data/devwebapp/config" -}}
          export username={{ .Data.data.username }}
          export password={{ .Data.data.password }}
          {{ end -}}  
        # vault.hashicorp.com/agent-inject-template-config.txt: |
        #   {{`{{ with secret "secret/data/devwebapp/config" }}
        #   {{ range $k, $v := .Data.data }}
        #     export {{ $k }}={{ $v }}
        #   {{ end }}
        #   {{ end }}`}}
      labels:
        app: nginx
    spec:
      serviceAccountName: vault
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "source /vault/secrets/config.txt"]


