kind: Service
apiVersion: v1
metadata:
  name: sampleweb
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      #destination port
      # targetPort: 8080
      # targetPort: nginx-port
